### ISSUE TITLE
Add Functional Tests for Author Endpoints

### ISSUE THREAD

**Issue by ardalis** [ardalis/ApiEndpoints#1]
Use this as a model/starting point:
https://github.com/ardalis/CleanArchitecture/blob/master/tests/CleanArchitecture.FunctionalTests/Api/ApiToDoItemsControllerList.cs

**Comment by KyleMcMaster** [comment]
I'll take a shot at implementing these functional tests! 😃

**Comment by ardalis** [comment]
Go for it!

**Comment by KyleMcMaster** [comment]
@ardalis I finished the get and list tests, but I ran into some issues with the create, delete, and update tests. I can open the PR for reference, but my issue is the in memory database provider causes some synchronization issues when the tests run. So when I run the create test, the total count of Authors is incremented which breaks the list test. Same goes for delete tests when it decrements the Author list count. I would appreciate any thoughts or feedback on how to approach these functional tests.

**Comment by ardalis** [comment]
If you want to PR just the read-only method tests that's fine.

If you want an example of some tests that I'm pretty sure work properly, look here:
https://github.com/ardalis/CleanArchitecture/tree/master/tests/CleanArchitecture.FunctionalTests

and also (older) here:
https://github.com/ardalis/GettingStartedWithFilters/tree/master/IntegrationTests

**Comment by KyleMcMaster** [comment]
Published the existing PR for get and list tests only for right now. If I have some additional availability over the next few days I'll gladly pick up the create, delete, and update tests if someone hasn't done them already.

**Comment by jeastham1993** [comment]
Happy to pick this up as well @ardalis for the create, update and delete methods

**Comment by ardalis** [comment]
Thanks!
