### ISSUE TITLE
Attribute routes with the same name 'HandleAsync' must have the same template

### ISSUE THREAD

**Issue by Mivaweb** [ardalis/ApiEndpoints#104]
- NuGet Package Version: 3.1.0
- .NET SDK Version: .NET Core 3.1

Steps to Reproduce:

1. Create a new endpoint List
2. Create a new endpoint Get

**List.cs**

    /// <summary>
    /// Customer List ApiEndpoint
    /// </summary>
    [Authorize]
    [Route("api/v{version:apiVersion}/customers")]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public class List : BaseAsyncEndpoint
        .WithoutRequest
        .WithResponse<IList<CustomerResponse>>
    {
        private readonly ICustomerRepository _customerRepository;
        private readonly IMapper _mapper;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="customerRepository"></param>
        /// <param name="mapper"></param>
        public List(ICustomerRepository customerRepository,
            IMapper mapper)
        {
            _customerRepository = customerRepository ?? throw new ArgumentNullException("ICustomerRepository can't be null.");
            _mapper = mapper ?? throw new ArgumentNullException("IMapper can't be null.");
        }

        /// <summary>
        /// Get a list of customers
        /// </summary>
        /// <param name="cancellationToken"></param>
        /// <returns>A list of customer objects</returns>
        [HttpGet(Name = nameof(List.HandleAsync))]
        [Authorize(Policy = "ApiCustomersRead")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public override async Task<ActionResult<IList<CustomerResponse>>> 
            HandleAsync(CancellationToken cancellationToken = default)
        {
            var result = await _customerRepository.GetAsync();

            return _mapper.Map<List<CustomerResponse>>(result);
        }
    }

**Get.cs**

    /// <summary>
    /// Customer Get ApiEndpoint
    /// </summary>
    [Authorize]
    [Route("api/v{version:apiVersion}/customers")]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public class Get : BaseAsyncEndpoint
        .WithRequest<Guid>
        .WithResponse<CustomerDetailResponse>
    {
        private readonly ICustomerRepository _customerRepository;
        private readonly IMapper _mapper;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="customerRepository"></param>
        /// <param name="mapper"></param>
        public Get(ICustomerRepository customerRepository,
            IMapper mapper)
        {
            _customerRepository = customerRepository ?? throw new ArgumentNullException("ICustomerRepository can't be null.");
            _mapper = mapper ?? throw new ArgumentNullException("IMapper can't be null.");
        }

        /// <summary>
        /// Get a customer
        /// </summary>
        /// <param name="customerId">The unique identifier of the customer</param>
        /// <param name="cancellationToken"></param>
        /// <returns>A customer object</returns>
        [HttpGet("{customerId:guid}", Name = nameof(Get.HandleAsync))]
        [Authorize(Policy = "ApiCustomersRead")]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public override async Task<ActionResult<CustomerDetailResponse>> 
            HandleAsync(Guid customerId, CancellationToken cancellationToken = default)
        {
            var result = await _customerRepository.GetByKeyAsync(customerId);

            if (result == null)
                throw new SkycountCustomerNotFoundException(customerId);

            return _mapper.Map<CustomerDetailResponse>(result);
        }
    }

After running the API I got the following exception:

```
InvalidOperationException: The following errors occurred with attribute routing information:

Error 1:
Attribute routes with the same name 'HandleAsync' must have the same template:
Action: 'Skycount.Finance.Web.v1_0.Endpoints.Customers.Get.HandleAsync (Skycount.Finance.Web)' - Template: 'api/v{version:apiVersion}/customers/{customerId:guid}'
Action: 'Skycount.Finance.Web.v1_0.Endpoints.Customers.List.HandleAsync (Skycount.Finance.Web)' - Template: 'api/v{version:apiVersion}/customers'
```

**Comment by Mivaweb** [comment]
Ok can be closed. When posting it here I see the issue lies in `[HttpGet("{customerId:guid}", Name = nameof(Get.HandleAsync))]`. After changing the nameof to a static unique string for each endpoint, the exception is gone and the API is working.

**Comment by ardalis** [comment]
Thanks for sharing your resolution. Also FYI you might appreciate using a shared library for this kind of thing:

`_customerRepository = customerRepository ?? throw new ArgumentNullException("ICustomerRepository can't be null.");`

[Ardalis.GuardClauses](https://github.com/ardalis/GuardClauses) would make this:

`_customerRepository = Guard.Against.Null(customerRepository, nameof(customerRepository);`

which isn't that much shorter, but there are no magic strings and it's more consistent.

Cheers!

**Comment by Mivaweb** [comment]
Thanks for the headsup on the GuardsClauses. Will look into it.

One more question, can be create another abstract base class of the `BaseAsyncEndpoint` which contains some IoC properties which are being used by many endpoints. 

For instance IMapper ( Automapper ), because now I have to include this property each time in the Endpoint.

Thanks!

**Comment by ardalis** [comment]
For something like that I would probably just use property injection and let the DI container provide it. Normally I'm not a fan of property injection but for controllers it makes sense since nobody should be manually instantiating those classes. I show an example of how to do this (with IMediator) here: 

https://ardalis.com/moving-from-controllers-and-actions-to-endpoints-with-mediatr/

**Comment by Mivaweb** [comment]
Thnx for the help @ardalis . One more question. I am looking to group the .cs files with endpoint / command / result like in your example. How did you managed this? Working with VS 2019 here.

Thanks!

**Comment by ErikEJ** [comment]
It is an ASP.NET Core project feature, so your project must be ASP.NET Core, or you can use https://marketplace.visualstudio.com/items?itemName=MadsKristensen.FileNesting

**Comment by ardalis** [comment]
Right, what @ErikEJ said. You need to follow a convention:

```
Foo.cs
Foo.SomeRequest.cs
Foo.SomeResponse.cs
```

As long as you prefix your sub-types with the name of the type they should nest under, it should work. Bonus, they will sort correctly (but not nest) by default in other editors like VS Code.
