### ISSUE TITLE
Render the absolute url for a given endpoint

### ISSUE THREAD

**Issue by Mivaweb** [ardalis/ApiEndpoints#116]
NuGet Package Version: 3.1.0
.NET SDK Version: .NET Core 3.1

I am trying to render the absolute url for a given endpoint using IUrlHelper but I can't get this to work.
I am using NamespaceConventions for my endpoints.

Example endpoint:

    ```
    /// <summary>
    /// Customer List ApiEndpoint
    /// </summary>
    [Authorize]
    [Route("api/v{version:apiVersion}/customers")]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public class List : BaseAsyncEndpoint
        .WithoutRequest
        .WithResponse<IList<CustomerListResponse>>
    {
        private readonly ICustomerService _customerService;
        private readonly IMapper _mapper;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="customerService"></param>
        /// <param name="mapper"></param>
        public List(
            ICustomerService customerService,
            IMapper mapper)
        {
            _customerService = Guard.Against.Null(customerService, nameof(customerService));
            _mapper = Guard.Against.Null(mapper, nameof(mapper));
        }

        /// <summary>
        /// Get a list of customers
        /// </summary>
        /// <param name="cancellationToken"></param>
        /// <returns>A list of customer objects</returns>
        [HttpGet(Name = "GetCustomers")]
        [Authorize(Policy = "ApiCustomersRead")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public override async Task<ActionResult<IList<CustomerListResponse>>> 
            HandleAsync(CancellationToken cancellationToken = default)
        {
            var customers = await _customerService.GetAsync();

            return _mapper.Map<List<CustomerListResponse>>(customers);
        }
    }
    ```

I need to get the url as:

/api/v1.0/customers

Any idea on how to do this?

When using controllers and without apiVersion I used IUrlHelper and passed controller name and action method:

url.RouteUrl(new { controller = apiControllerName, action = actionName });

**Comment by ardalis** [comment]
Did you figure it out? What was the trick?

**Comment by Mivaweb** [comment]
Nope didn't found a solution.

Had issues with the apiVersion and also because I was pointing from another Web project ( my frontend web projeect ) where the startup settings were different then my API project I couldn't get this working in a nice way.

Was trying to make something dynamic to go over all endpoints and render the base url to be exposed in a javascript tag to my VueJS application on startup of the Home controller Index view. So I can use this in my VueJS without hardcoding the baseurls.

I have now created a static class with all base urls as string const properties and then exposed these as json to the frontend.

For now its sufficient because these won't change frequently or never but don't like it 100% because of manual string initialization.
