### ISSUE TITLE
Allow multiple query string parameters

### ISSUE THREAD

**Issue by jeastham1993** [ardalis/ApiEndpoints#15]
I can't seem to discover a way to provide multiple query string parameters into a single endpoint, the type params of BaseRequest only support a single request/response.

A use case being something like pagination

GET https://myapi/v1/transactions?page=1&per_page=10&query=1234

I'm happy to implement it, if you have any suggestions on how.

**Comment by ardalis** [comment]
I had someone else point out how to overcome this. I haven't had a chance to implement it but I'll track it down and do so.

**Comment by jeastham1993** [comment]
If you manage to track it down send through the code and I'm happy to do the legwork.

**Comment by ardalis** [comment]
Try this: https://github.com/ardalis/ApiEndpoints/issues/6

**Comment by ardalis** [comment]
Fixed, thanks!
