### ISSUE TITLE
ModelState is always Valid

### ISSUE THREAD

**Issue by babaktaremi** [ardalis/ApiEndpoints#167]
Hi I'm using the latest version on NET6 and using RequiredAttribute on request models. But the ModelState is always valid. What seems to be the problem?

**Comment by ardalis** [comment]
1. Which version is latest? v3 or v4-prerelease?
2. Can you show your endpoint and its associated request model?

**Comment by babaktaremi** [comment]
> 1. Which version is latest? v3 or v4-prerelease?
> 2. Can you show your endpoint and its associated request model?

I Created a NET 6 Template and added to following code to the Program.cs class to suppress the default behaviour of modelstate validation in asp. net core

```csharp
builder.Services.AddControllers().ConfigureApiBehaviorOptions(c => c.SuppressModelStateInvalidFilter = true);
```

then I Created a simple model for login

```csharp
public class LoginRequest
    {
        [Required]
        public string UserName { get; set; }

        [Required]
        public string Password { get; set; }
    }
```

and the related endpoint like this
```csharp
  [ApiController]
    [Route("Api/User")]
    public class Login:BaseAsyncEndpoint.WithRequest<LoginRequest>.WithoutResponse
    {
        [HttpPost("Login")]
        public override async Task<ActionResult> HandleAsync(LoginRequest request, CancellationToken cancellationToken = new CancellationToken())
        {
            if (!ModelState.IsValid)
                return BadRequest("Not Valid");

            return Ok("Valid");
        }
    }
```

The Value of ```ModelState.IsValid``` is always true. regardless of the state of the ```LoginRequest``` properties.
 the version I'm currently using is ```3.1.0```

**Comment by ardalis** [comment]
Why are you suppressing model state invalid? Given that you're doing that, isn't this behaving as expected?

**Comment by ardalis** [comment]
Let me know if this is still an issue - closing for now.
