### ISSUE TITLE
Docs: Add a sample showing how to do a file upload

### ISSUE THREAD

**Issue by ardalis** [ardalis/ApiEndpoints#170]

**Comment by jonathanjameswilliams26** [comment]
Any update on this? Do you know where I can find an example?

**Comment by belavenuto** [comment]
@jonathanjameswilliams26 did you manage to find a way to do the file upload?

**Comment by jonathanjameswilliams26** [comment]
@belavenuto Yeah I was able to use the `[FromForm]` attribute on my request dto.
```csharp
public record UploadFileRequest
{
      [FromForm]
      public IFormFile File { get; set; }
}
```

And this is what I had to use in postman
![image](https://user-images.githubusercontent.com/37890156/164441190-a7a8f929-0200-4fab-b7c7-a38ce420780d.png)

**Comment by belavenuto** [comment]
@renannn it worked for me. This is my endpoint:

`
public class PurchaseOrderReadXml : EndpointBaseAsync
    .WithRequest<PurchaseOrderUploadXmlRequest>
    .WithActionResult<PurchaseOrderDto>
`

The handle method:

`
public override async Task<ActionResult<PurchaseOrderDto>> HandleAsync(
    [FromForm] PurchaseOrderUploadXmlRequest request,
    CancellationToken cancellationToken)
  {`

The DTO:

`
public class PurchaseOrderUploadXmlRequest
{
  [FromForm]
  public IFormFile? File { get; set; }
}`

**Comment by mariusz96** [comment]
Why would it work any differently than on a normal controller?

Using the sample, for example:
```cs
using Ardalis.ApiEndpoints;
using Microsoft.AspNetCore.Mvc;

namespace SampleEndpointApp.Endpoints.Authors;

public class File : EndpointBaseAsync
    .WithRequest<IFormFile>
    .WithResult<ActionResult<string[]>>
{
  /// <summary>
  /// Post author's photo or something
  /// </summary>
  [HttpPost("api/[namespace]/file")]
  public override async Task<ActionResult<string[]>> HandleAsync(
    IFormFile file,
    CancellationToken cancellationToken = default)
  {
    using var memoryStream = new MemoryStream();
    await file.CopyToAsync(memoryStream, cancellationToken);

    string path = Path.GetTempFileName();
    await System.IO.File.WriteAllBytesAsync(path, memoryStream.ToArray(), cancellationToken);

    return new[]
    {
      path,
      file.FileName,
      file.ContentType,
      file.ContentDisposition,
      file.Length.ToString()
    };
  }
}
```

Works OK with Swagger and Postman.

Model binding docs: https://learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-7.0#sources.

**Comment by ardalis** [comment]
Thanks @mariusz96 !
