### ISSUE TITLE
Grouping together operations for the swagger document

### ISSUE THREAD

**Issue by curelom** [ardalis/ApiEndpoints#178]
It appears that the way you document how to group together the endpoints using the swaggeroperation attribute is being deprecated.  I have found using the OpenApiTag attribute works in it's stead.

[OpenApiTag("Patients")]

**Comment by maxkoshevoi** [comment]
Try using: https://www.nuget.org/packages/Ardalis.ApiEndpoints.Swashbuckle/
It allows grouping actions based by namespace (seems that documentation for the package is yet to be done)

You can look at how it's done in the sample: https://github.com/ardalis/ApiEndpoints/blob/main/sample/SampleEndpointApp/Startup.cs#L37

**Comment by curelom** [comment]
Maxkoshevoi had the answer
