### ISSUE TITLE
Add async support

### ISSUE THREAD

**Issue by awright18** [ardalis/ApiEndpoints#2]
BaseEndpoint should support Task based options because many people use async tasks for IO.

**Comment by ardalis** [comment]
Definitely! Thanks!

**Comment by ardalis** [comment]
Also need to update the sample to show an async repository or something similar.

**Comment by ardalis** [comment]
Based on this thread I think it's still important to use the Async suffix, though I was hoping perhaps to drop it:
https://github.com/dotnet/runtime/issues/26908
