### ISSUE TITLE
Example on how to tackle Duplicate Code in Endpoints

### ISSUE THREAD

**Issue by neotrow** [ardalis/ApiEndpoints#200]
In the samples it's mentioned that you can create your own `AppEndpointBaseSync ` that inherrit from `EndpointBaseSync`. 
But I don't see how this would work since `EndpointBaseSync` is a static class. An example of how this can be achieved would be great! 

ref: 
https://github.com/ardalis/ApiEndpoints/tree/be0f270389b604d6b291c3e2ae3338a4568bbb37/sample/SampleEndpointApp

**Comment by ardalis** [comment]
You're right, that wouldn't work as written.

I've updated it:
> If the duplicate dependency code in the endpoints bothers you, you can avoid it easily by creating your own AppEndpointBaseSync classes that inherit from EndpointBaseSync. These can expose as properties any common dependencies like loggers, mappers, or generic repositories, and then use an IOC container's property injection feature to ensure they're always populated when the endpoint is created.

Which isn't quite as nice but should work.
