### ISSUE TITLE
Minimal Apis

### ISSUE THREAD

**Issue by veldfolds** [ardalis/ApiEndpoints#201]
I like api endpoints but I'm confused about how this fits in with the new minimal APIs, Can this library be oriented in that direction or is it an alternative as it is.

**Comment by ardalis** [comment]
This library is built on MVC and Controllers. For the same [REPR ](https://deviq.com/design-patterns/repr-design-pattern) pattern approach built on the newer minimal APIs I recommend [Fast Endpoints](https://fast-endpoints.com/).
