### ISSUE TITLE
Update Getting Started section

### ISSUE THREAD

**Issue by mariusz96** [ardalis/ApiEndpoints#202]
Hi,

After installing the nuget package I started to look for some getting started / quickstart guide.

It seems that [the current one](https://github.com/ardalis/ApiEndpoints#3-getting-started) references types that no longer exists: `EndpointBaseSync<TRequest,TResponse>`, `EndpointBaseSync<TResponse>` and needs to be updated.

**Comment by ardalis** [comment]
The /sample folder is probably your best option for getting started and seeing how things work. But yes, the docs/README should be updated as well.
