### ISSUE TITLE
Ability to have RequestBody object, but also Request Query.

### ISSUE THREAD

**Issue by chris-briddock** [ardalis/ApiEndpoints#207]
Please implement static member of WithRequestBody and WithRequestQuery and of course that will have two object params.

Or you could add an optional param to WithRequest and add a second object param.

At the moment, it is all in the body, or all in the query.

**Comment by ardalis** [comment]
Can't you achieve this now by using a composite request type and `[FromQuery]` and `[FromBody]` as appropriate?

**Comment by ardalis** [comment]
I don't see a link to your fork, though.

**Comment by chris-briddock** [comment]
https://github.com/chris-briddock/ChristopherBriddock.ApiEndpoints

I know you can do this by using the FromQuery attribute on the properties within the Request object. Perhaps have With and Without QueryRequest?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
