### ISSUE TITLE
Migrating to the controller-less pattern

### ISSUE THREAD

**Issue by justSteve** [ardalis/ApiEndpoints#34]
This sentence: _The .NET team already did this exact thing with razor pages._ really brought home for me the bigger picture. I'm ready to buy in 100%. If the old way was _controllers mainly for sake of routes_ (opened the door for bloated controllers with too many dependencies) - then this 'razor-pages-for-apis' approach is the basically replacing the conventional controller with a CQRS pattern, isn't it? 

And ApiEndpoints gives us linked files which overcomes what used to be very awkward -- navigated between where the event was raised and where the handler's code sat, yes? 

How exactly are these files being linked so they show in VS as they do?

**Comment by ardalis** [comment]
Glad you like the library/pattern! The visual studio file linking is a built-in feature. You just have to name the files appropriately and it will take care of it automatically.

**Comment by justSteve** [comment]
Another question falling under the same '_migrating to controller-less_' topic: logging. My habit has been to log fairly heavily in the controller -- even to the point of logging out all the full (json) payload of submitted posts. This would not probably be considered 'best practice' but in my particular niche it proved extremely effective. 

This sample app seems to have no logging at all. https://github.com/ardalis/CleanArchitecture shows a single log statement in EmailSender (in the Infrastructure project). Any guidance for logging a CleanArchitecture app built using ApiEndpoints?

**Comment by phlashdev** [comment]
@justSteve in case you still need a solution for this, there is an official blog post coming from Microsoft where it is shown how you can log and rewind the request body: https://devblogs.microsoft.com/aspnet/re-reading-asp-net-core-request-bodies-with-enablebuffering/

I used this in some projects myself, had no problems whatsoever.

**Comment by ardalis** [comment]
@justSteve I just inject a logger as a constructor dependency anywhere I need one.
