### ISSUE TITLE
Authorization support

### ISSUE THREAD

**Issue by jmanuelcorral** [ardalis/ApiEndpoints#40]
Hi,

  I'm very interested in this design, but I have not found in documentation how to setup the [Authorize] decorator. Is this possible?
  If I create for example a custom Authentication Handler, for execute a policy, i will work with this solution?

  Congratulations for that amazing work.  

Thanks.
Jose.

**Comment by jmanuelcorral** [comment]
I have read the source and I understand 👍

**Comment by kjbetz** [comment]
@jmanuelcorral So, what's the answer? Can you elaborate? Can we just put `[Authorize]` attributes on the class/method?

**Comment by jmanuelcorral** [comment]
Yes at first moment, I think the author was doing something different than a base controller class, with this endpoints, When I review the code I see that I was wrong, yes, you only have to use Authorize attribute or policies or whatever you want. 😊

**Comment by kjbetz** [comment]
Awesome, thanks for the reply! I'll check it out and then maybe will add to examples.
