### ISSUE TITLE
Make Ardalis.ApiEndpoints.CodeAnalyzers less coupled with ApiEndpoints project

### ISSUE THREAD

**Issue by Lonli-Lokli** [ardalis/ApiEndpoints#41]
I would like to use your approach with one single action per controller but don't want to inherit from BaseEndpoint as it will be tricky to update all current methods for Handle usage.

Instead I would like to create my own empty Endpoint base class and reuse your CodeAnalyzer with autofix behaviour to create separate endpoint files per action.

**Comment by ardalis** [comment]
Probably you could modify it to work on any `Controller` instead of `BaseEndpoint`.

**Comment by Lonli-Lokli** [comment]
Yep, but I don't want to fork and publish it for my needs, I would prefer to use this package as  it is.
also it's locked not only on base class but on abstract methods as well

**Comment by ardalis** [comment]
Sure but if we changed this one to be less focused, it would throw a bunch of warnings in codebases for folks who are mixing endpoints with standard controllers, which I doubt they would appreciate unless their intent was to migrate everything to endpoints. Right? I think a separate package with just a "SlimControllersAnalyzer" would make more sense. Agree?
