### ISSUE TITLE
Swagger 'Fetch Error' and optional parameters via query string

### ISSUE THREAD

**Issue by terryaney** [ardalis/ApiEndpoints#43]
1. If you have an endpoint with an `[HttpGet( "/calc-engines/{name}" )]` attribute but you want to accept optional query string parameters (i.e. `bool? allVersions`), how do you declare your `BaseAsyncEndpoint`?

I have `public class Get : BaseAsyncEndpoint<Get.Query, Get.CalcEngine[]>` and then have a Query object with `name` and `allVersions` properties, but when I hit swagger, it shows this:

![image](https://user-images.githubusercontent.com/6237247/105921768-e6983a00-5ffe-11eb-9949-55678a41396b.png)

New to creating web apis, is the 'optional' values on the querystring bad practice?  Note that I have a `[HttpGet( "/calc-engines" )]` route that returns all information versus detailed information for one item.

2. Swagger issue (and I can't seem to find any logging saying why it is failing).  When I only had one endpoint, everything worked great.  But when I added two endpoints, I received:

> Fetch error
> undefined /swagger/v1/swagger.json

The following shows my endpoint code.  Both are essentially the same and I haven't decided if I'm keeping MediatR or not, but I haven't yanked out yet so just pasting.  Note that if I remove one or the other, Swagger works, only fails when both are present.

```
public class Get : BaseAsyncEndpoint<List.Query, List.CalcEngine[]>
{
	private readonly IMediator mediator;

	public Get( IMediator mediator ) => this.mediator = mediator;

	[HttpGet( "/calc-engines/{name}" )]
	[SwaggerOperation(
		Summary = "Get detailed information about a CalcEngine",
		Description = "Get Live and Test CalcEngine information and all prior version information for each",
		OperationId = "CalcEngines.Get",
		Tags = new[] { "CalcEngines" } )
	]
	public async override Task<ActionResult<CalcEngine[]>> HandleAsync(
		[FromQuery] query,
		CancellationToken cancellationToken = default ) => await mediator.Send( query, cancellationToken );

	public record Query : IRequest<CalcEngine[]>
	{
		public string name { get; init; }
		public bool allVersions { get; init; } = false;
	}

	public record CalcEngine
	{
		public string Name { get; init; }
		...
	}

	class Handler : IRequestHandler<Query, CalcEngine[]>
	{
		public Task<CalcEngine[]> Handle( Query message, CancellationToken token )
		{
			var results = new[]
			{
				new CalcEngine ...
				new CalcEngine ...
			};

			return Task.FromResult( results );
		}
	}
}
```

Thanks in advance.

**Comment by terryaney** [comment]
I discovered the cause for item 2 above and I submitted [an issue to Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1972).  Curious on best route for item 1 though.

**Comment by ardalis** [comment]
I think the solution is to use attributes on the parameters to the Handle action method (or on the properties of the DTO that is being used as a parameter, like in your example above). If this is working for you I'll try to add it to the documentation so others see how to do it as well.

**Comment by ardalis** [comment]
Also for your first issue you were led here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-schema-ids

What did you ultimately use from that link that helped?

**Comment by terryaney** [comment]
I used this: https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-schema-ids and also removed the 'superfluous' namespace part to keep it shorter and only add enough of the FullName to make it distinct.

```
c.CustomSchemaIds( type =>
{
	return type.FullName
			.Replace( "Microsoft.AspNetCore.Mvc.", "" )
			.Replace( "BTR.Camelot.Api.DataLocker.Endpoints.", "" )
			.Replace( "BTR.Camelot.Api.DataLocker.Models.", "" );
} );
```

**Comment by ardalis** [comment]
Closing; this looks like it's solved.
