### ISSUE TITLE
Suggestion: using fluent generics

### ISSUE THREAD

**Issue by paulvanbladel** [ardalis/ApiEndpoints#44]
Inspired by this article: https://tyrrrz.me/blog/fluent-generics
I tried it here:
see: https://github.com/paulvanbladel/ApiEndpoints

It's about making the endpoint signature more expressive by using :
```
 public class Create : Endpoint.WithRequest<CreateAuthorCommand>.WithResponse<CreateAuthorResult>
    {
        private readonly IAsyncRepository<Author> _repository;
        private readonly IMapper _mapper;

        public Create(IAsyncRepository<Author> repository,
            IMapper mapper)
        {
            _repository = repository;
            _mapper = mapper;
        }

        [HttpPost("/authors")]
        [SwaggerOperation(
            Summary = "Creates a new Author",
            Description = "Creates a new Author",
            OperationId = "Author.Create",
            Tags = new[] { "AuthorEndpoint" })
        ]
```

**Comment by ardalis** [comment]
I love it! That article is great and it's describing a real problem I ran into.

It's a breaking change but one I think is worth making. Do you want to PR your fork and its updates? Perhaps update the README slightly to point to tyrrz's article as a reference, too?

If not I'll try to get to it but your fork looks good after I took a quick look.

**Comment by paulvanbladel** [comment]
Sure, pleasure to make a PR.
Keep you posted.
Cheers
