### ISSUE TITLE
How to use CreatedAt* action result helpers

### ISSUE THREAD

**Issue by terryaney** [ardalis/ApiEndpoints#46]
None of the `CreatedAt*` methods nor the `LinkGenerator` are able to create urls under pattern (for me at least).

Are there any work arounds?  My signature looks like this

```
[HttpGet( Routes.Files.Download )]
[SwaggerOperation(
	Summary = "Download file",
	Description = "Download file",
	OperationId = "Files." + nameof( Routes.Files.Download ),
	Tags = new[] { "Files" } )]
[SwaggerOrder( 2 )]
[ProducesResponseType( typeof( FileStreamResult ), StatusCodes.Status200OK )]
[ProducesResponseType( StatusCodes.Status304NotModified )]
[ProducesResponseType( typeof( ValidationProblemDetails ), StatusCodes.Status401Unauthorized )]
[ProducesResponseType( typeof( ValidationProblemDetails ), StatusCodes.Status404NotFound )]
public async Task<IActionResult> HandleAsync( [FromQuery] Parameters parameters ) => await DownloadFileAsync( parameters.Id, dbConnectionFactory );
```

And the class name is `Download`.

`linkGenerator.GetPathByAction( nameof( Download.HandleAsync ), nameof( Download ), new { id = fileId } );` returns `null` and `return CreatedAtAction( nameof( Download.HandleAsync ), nameof( Download ), new { Id = fileId } );` throws an exception.

> System.InvalidOperationException: No route matches the supplied values.
>    at Microsoft.AspNetCore.Mvc.CreatedAtRouteResult.OnFormatting(ActionContext context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
>    at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
>

**Comment by ardalis** [comment]
Can you show the source of the `DownloadFileAsync` method? I'm not seeing where the actual CreatedAtAction is being created/used/returned.

**Comment by terryaney** [comment]
Sorry, trying to read my post and see where I went wrong and how I have it working now, but I can't even decipher it.  It must have been a long night.  The following `CreatedAtRoute` works (inside `DownloadFIleAsync`)

```
var fi = /* object */;
return CreatedAtRoute(
	nameof( Routes.Files ) + "." + nameof( Routes.Files.Get ),
	new { Id = fi.FileKey },
	new DataLockerFileItemResult { Item = fi }
);
```
Then I just decorate my `Get` method as:

```
[HttpGet( Routes.Files.Get, Name = nameof( Routes.Files ) + "." + nameof( Routes.Files.Get ) )]
public async Task<IActionResult> HandleAsync( [FromQuery] Parameters parameters ) => await GetFileAsync( parameters.Id, dbConnectionFactory );
```

**Comment by ardalis** [comment]
Seems like you have it working; closing.
