### ISSUE TITLE
Question - How do we reuse/share the same models between endpoints to keep it DRY? 

### ISSUE THREAD

**Issue by VishnuPrabhuT** [ardalis/ApiEndpoints#51]
Please be gentle if it's a dumb question. 😅

**Comment by ardalis** [comment]
I usually have an Endpoints folder per type of thing (basically where you would have used a Controller class I would use a folder.

In that folder all of the endpoint-specific requests and responses are associated with their endpoint using a naming convention:
Create.cs
Create.CreateCustomerRequest.cs
Create.CreateCustomerResponse.cs

This will show up in Visual Studio as an expandable linked set of files.

But if you have a common `CustomerDTO` that is used in multiple requests/responses, you can just put it in the Endpoints folder so it's right there with everything that uses it. If you don't like that, you can put it somewhere else - it's entirely up to you.

**Comment by ardalis** [comment]
See also: https://stackoverflow.com/questions/67110664/how-do-we-share-reuse-the-same-models-between-api-endpoints-to-keep-things-dry/67110665#67110665
