### ISSUE TITLE
Complex Request Model ApiController and QueryString params

### ISSUE THREAD

**Issue by StevenTCramer** [ardalis/ApiEndpoints#6]
I think you will have problems binding to Complex Models if from query params if you don't 
SuppressInferBindingSourcesForParameters.

Once you have a test case you can confirm that and then the following should fix it :)

```
      aServiceCollection.Configure<ApiBehaviorOptions>
      (
        aApiBehaviorOptions =>
        {
          aApiBehaviorOptions.SuppressInferBindingSourcesForParameters = true;
        }
      );
```

**Comment by ardalis** [comment]
This means anyone using this will need to mess with their `Startup` class, eh?

**Comment by dasiths** [comment]
oh wow I just implemented the same pattern (https://github.com/dasiths/SimpleEndpoint). Great minds haha. 

To get around the `[FromQuery]` complex type binding problem the BaseController should not be decorated with [ApiController]. If you decorate it with `[ApiController]`  you get everything here (https://kimsereyblog.blogspot.com/2018/08/apicontroller-attribute-in-asp-net-core.html) for free but unfortunately it includes `Inferring Binding Sources For Parameters` so the complex object ignores [FromQuery] and tries to bind using the Body.

So let the end users decorate the Controller with the attribute as they see fit. `ControllerBase` already has `[Controller]` attribute decoration so it works for most cases out of the box. Some of my examples are here https://github.com/dasiths/SimpleEndpoint/tree/master/SimpleEndpoint.Example/Controllers

I'll add few more in the next few days.

**Comment by ardalis** [comment]
I think this is fixed now.
