### ISSUE TITLE
Consolidate current pipelines into a single pipeline with additional features

### ISSUE THREAD

**Issue by szlatkow** [ardalis/ApiEndpoints#77]
A single GitHub Actions pipeline for all the required automated processes to eliminate potentially unnecessary overhead of maintaining several separate pipelines.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by ojrojas** [comment]
Hi Ardalis, please consider adding a custom return type for File types
`  public abstract class WithResponseCustoms<TResponse> : BaseEndpointAsync
            {
                public abstract Task<TResponse> HandleAsync(
                    TRequest request,
                    CancellationToken cancellationToken = default
                );
            }`

**Comment by ardalis** [comment]
@ojrojas moving this to its own issue #81
